include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    - avoid_void_async
    - prefer_single_quotes
    - unawaited_futures
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - unnecessary_await_in_return
    - use_string_buffers
    - prefer_relative_imports
